sonar.projectKey=sqp_48702c8f7c999de466ba367a9819112f7034844e
sonar.sources=.
sonar.exclusions=.venv/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=results.xml
sonar.tests=tests