"""Voeg mappen en documenten tabellen toe

Revision ID: 3a9f507bc435
Revises: ad8c2bb96f21
Create Date: 2026-07-21 17:38:46.505304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9f507bc435'
down_revision = 'ad8c2bb96f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('aangemaakt_door_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aangemaakt_door_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['mappen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mappen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mappen_organisatie_id'), ['organisatie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mappen_parent_id'), ['parent_id'], unique=False)

    op.create_table('documenten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('bestandsnaam', sa.String(length=255), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('bestandsgrootte', sa.Integer(), nullable=False),
    sa.Column('inhoud', sa.LargeBinary(), nullable=False),
    sa.Column('versie', sa.Integer(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('aangemaakt_door_id', sa.Integer(), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(), nullable=False),
    sa.Column('gewijzigd_door_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aangemaakt_door_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gewijzigd_door_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['mappen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documenten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documenten_map_id'), ['map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documenten_organisatie_id'), ['organisatie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documenten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documenten_organisatie_id'))
        batch_op.drop_index(batch_op.f('ix_documenten_map_id'))

    op.drop_table('documenten')
    with op.batch_alter_table('mappen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mappen_parent_id'))
        batch_op.drop_index(batch_op.f('ix_mappen_organisatie_id'))

    op.drop_table('mappen')
    # ### end Alembic commands ###
