"""add reset_pogingen to user

Revision ID: 3c49eab9a595
Revises: 8b27e2ddebf7
Create Date: 2026-07-24 09:15:17.640690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c49eab9a595'
down_revision = '8b27e2ddebf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_pogingen', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_pogingen')

    # ### end Alembic commands ###
