"""add_tekst_inhoud_to_documenten

Revision ID: 3d2524a3c6d4
Revises: f1a8c9e2b345
Create Date: 2026-09-03 10:48:29.239142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2524a3c6d4'
down_revision = 'f1a8c9e2b345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documenten', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tekst_inhoud', sa.Text(), nullable=True))

    # Backfill bestaande documenten
    bind = op.get_bind()
    try:
        from utils.text_extractor import extraheer_tekst_uit_bestand
        docs_table = sa.table(
            'documenten',
            sa.column('id', sa.Integer),
            sa.column('bestandsnaam', sa.String),
            sa.column('mime_type', sa.String),
            sa.column('inhoud', sa.LargeBinary),
            sa.column('tekst_inhoud', sa.Text)
        )
        results = bind.execute(sa.select(docs_table.c.id, docs_table.c.bestandsnaam, docs_table.c.mime_type, docs_table.c.inhoud)).fetchall()
        for doc_id, bestandsnaam, mime_type, inhoud in results:
            if inhoud:
                tekst = extraheer_tekst_uit_bestand(bytes(inhoud), bestandsnaam, mime_type)
                if tekst:
                    bind.execute(
                        docs_table.update().where(docs_table.c.id == doc_id).values(tekst_inhoud=tekst)
                    )
    except Exception as e:
        print(f"Waarschuwing bij backfill van documenttekst: {e}")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documenten', schema=None) as batch_op:
        batch_op.drop_column('tekst_inhoud')

    # ### end Alembic commands ###
