"""multitenant

Revision ID: 3fc6cbbf9830
Revises: c4d8e2f6a1b3
Create Date: 2026-07-15 20:49:24.803545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc6cbbf9830'
down_revision = 'c4d8e2f6a1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organisaties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisaties_slug'), ['slug'], unique=True)

    # Voeg default organisatie toe
    op.execute("INSERT INTO organisaties (id, naam, slug, actief, aangemaakt_op) VALUES (1, 'Digidokters', 'digidokters', 1, CURRENT_TIMESTAMP)")

    op.create_table('user_organisaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organisatie_id', name='uq_user_organisatie')
    )

    # Kopieer bestaande gebruikers naar de default organisatie
    op.execute(
        "INSERT INTO user_organisaties (user_id, organisatie_id, rol, actief, aangemaakt_op) "
        "SELECT id, 1, rol, actief, aangemaakt_op FROM users"
    )

    with op.batch_alter_table('age_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisatie_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_unique_constraint('uq_age_category_org_naam', ['organisatie_id', 'naam'])
        batch_op.create_foreign_key('fk_age_category_organisatie', 'organisaties', ['organisatie_id'], ['id'])

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisatie_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_unique_constraint('uq_device_org_naam', ['organisatie_id', 'naam'])
        batch_op.create_foreign_key('fk_device_organisatie', 'organisaties', ['organisatie_id'], ['id'])

    with op.batch_alter_table('digidokters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisatie_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_unique_constraint('uq_digidokter_org_naam', ['organisatie_id', 'naam'])
        batch_op.create_foreign_key('fk_digidokter_organisatie', 'organisaties', ['organisatie_id'], ['id'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisatie_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.drop_index(batch_op.f('ix_registrations_registratienummer'))
        batch_op.create_index(batch_op.f('ix_registrations_registratienummer'), ['registratienummer'], unique=False)
        batch_op.create_unique_constraint('uq_registration_org_num', ['organisatie_id', 'registratienummer'])
        batch_op.create_foreign_key('fk_registration_organisatie', 'organisaties', ['organisatie_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_naam'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_naam'), ['naam'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_naam'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_naam'), ['naam'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_registration_org_num', type_='unique')
        batch_op.drop_index(batch_op.f('ix_registrations_registratienummer'))
        batch_op.create_index(batch_op.f('ix_registrations_registratienummer'), ['registratienummer'], unique=1)
        batch_op.drop_column('organisatie_id')

    with op.batch_alter_table('digidokters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_digidokter_org_naam', type_='unique')
        batch_op.drop_column('organisatie_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_device_org_naam', type_='unique')
        batch_op.drop_column('organisatie_id')

    with op.batch_alter_table('age_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_age_category_org_naam', type_='unique')
        batch_op.drop_column('organisatie_id')

    op.drop_table('user_organisaties')
    with op.batch_alter_table('organisaties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisaties_slug'))

    op.drop_table('organisaties')
    # ### end Alembic commands ###
