"""add_question_categories_and_classifications

Revision ID: 5cb3b9c18368
Revises: a1b2c3d4e5f6
Create Date: 2026-09-11 19:10:39.037474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb3b9c18368'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_categories_naam'), ['naam'], unique=True)

    op.create_table('question_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('zekerheid', sa.Float(), nullable=True),
    sa.Column('toelichting', sa.Text(), nullable=True),
    sa.Column('model_naam', sa.String(length=50), nullable=True),
    sa.Column('is_handmatig_aangepast', sa.Boolean(), nullable=False),
    sa.Column('aangepast_door_id', sa.Integer(), nullable=True),
    sa.Column('geclassificeerd_op', sa.DateTime(), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aangepast_door_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['question_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_classifications_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_classifications_registration_id'), ['registration_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_classifications_registration_id'))
        batch_op.drop_index(batch_op.f('ix_question_classifications_category_id'))

    op.drop_table('question_classifications')
    with op.batch_alter_table('question_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_categories_naam'))

    op.drop_table('question_categories')
    # ### end Alembic commands ###
