"""Voeg kleur toe aan ActivityType

Revision ID: 71543a345569
Revises: 7fb9b2ad7c0d
Create Date: 2026-07-21 21:18:54.364804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71543a345569'
down_revision = '7fb9b2ad7c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kleur', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.drop_column('kleur')

    # ### end Alembic commands ###
