"""Voeg reset code kolommen toe aan users

Revision ID: 7fb9b2ad7c0d
Revises: 3a9f507bc435
Create Date: 2026-07-21 20:23:18.932418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb9b2ad7c0d'
down_revision = '3a9f507bc435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_code_verloopt_op', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_code_verloopt_op')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
