"""add_evaluations_and_activity_type_flag

Revision ID: 8279b19fe421
Revises: ca7f46d39717
Create Date: 2026-08-31 20:38:06.841097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8279b19fe421'
down_revision = 'ca7f46d39717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluatie_formulieren',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=150), nullable=False),
    sa.Column('toelichting', sa.Text(), nullable=True),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisatie_id', 'activity_type_id', name='uq_eval_form_org_activity_type')
    )
    with op.batch_alter_table('evaluatie_formulieren', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluatie_formulieren_activity_type_id'), ['activity_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluatie_formulieren_organisatie_id'), ['organisatie_id'], unique=False)

    op.create_table('evaluatie_reacties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('digidokter_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ingediend_op', sa.DateTime(), nullable=False),
    sa.Column('antwoorden', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['digidokter_id'], ['digidokters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['evaluatie_formulieren.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_item_id', 'digidokter_id', name='uq_eval_response_agenda_digidokter')
    )
    with op.batch_alter_table('evaluatie_reacties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluatie_reacties_agenda_item_id'), ['agenda_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluatie_reacties_digidokter_id'), ['digidokter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluatie_reacties_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluatie_reacties_organisatie_id'), ['organisatie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluatie_reacties_user_id'), ['user_id'], unique=False)

    op.create_table('evaluatie_uitnodigingen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_item_id', sa.Integer(), nullable=False),
    sa.Column('digidokter_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('verzonden_op', sa.DateTime(), nullable=False),
    sa.Column('is_ingevuld', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['digidokter_id'], ['digidokters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_item_id', 'digidokter_id', name='uq_eval_invitation_agenda_digidokter')
    )
    with op.batch_alter_table('evaluatie_uitnodigingen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluatie_uitnodigingen_agenda_item_id'), ['agenda_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluatie_uitnodigingen_digidokter_id'), ['digidokter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluatie_uitnodigingen_token'), ['token'], unique=True)

    op.create_table('evaluatie_vragen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('vraag_tekst', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('opties', sa.JSON(), nullable=True),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.Column('verplicht', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['evaluatie_formulieren.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluatie_vragen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluatie_vragen_form_id'), ['form_id'], unique=False)

    op.add_column('activity_types', sa.Column('heeft_evaluatie', sa.Boolean(), server_default=sa.false(), nullable=False))

    # Data Seed: configureer Digicafé evaluatieformulier en vragen cross-database compatibel
    from datetime import datetime

    connection = op.get_bind()
    now_dt = datetime.utcnow()

    digicafe_vragen = [
        {
            'vraag_tekst': 'Hebben de deelnemers iets geleerd vandaag?',
            'type': 'multiple_choice',
            'opties': ['Niet veel', 'Een beetje', 'Redelijk wat', 'Veel', 'Heel veel'],
            'volgorde': 1,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Zou je dit Digicafé ook aan andere klanten van de Digidokters aanraden?',
            'type': 'multiple_choice',
            'opties': ['Ja', 'Ik twijfel', 'Nee'],
            'volgorde': 2,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Was het Digicafé goed opgebouwd en duidelijk?',
            'type': 'multiple_choice',
            'opties': ['Zeer goed', 'Goed', 'Matig', 'Slecht'],
            'volgorde': 3,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Was het lesmateriaal (zoals presentaties of oefeningen) nuttig en begrijpelijk?',
            'type': 'multiple_choice',
            'opties': ['Zeer goed', 'Goed', 'Matig', 'Slecht'],
            'volgorde': 4,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Hoe nuttig vond je deze les voor de digitale vaardigheden van de deelnemers?',
            'type': 'multiple_choice',
            'opties': ['Zeer goed', 'Goed', 'Matig', 'Slecht'],
            'volgorde': 5,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Was het onderwerp en de inhoud voor hen interessant en makkelijk te begrijpen?',
            'type': 'multiple_choice',
            'opties': ['Teveel informatie (te breed)', 'Perfect zo', 'Te weinig informatie'],
            'volgorde': 6,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Hoe vond je de verhouding tussen het theoretische gedeelte en de oefeningen?',
            'type': 'multiple_choice',
            'opties': ['Teveel theorie', 'Perfect zo', 'Teveel oefeningen'],
            'volgorde': 7,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Was er voldoende ruimte voor interactie tussen de groep en met de docent?',
            'type': 'multiple_choice',
            'opties': ['Te weinig interactie', 'Perfect zo', 'Teveel interactie'],
            'volgorde': 8,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Was het tempo van de docent goed afgestemd op het leertempo van de (meeste) deelnemers?',
            'type': 'multiple_choice',
            'opties': ['Te snel', 'Perfect zo', 'Te traag'],
            'volgorde': 9,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Heb je als Digidokter één of meer deelnemers persoonlijke ondersteund?',
            'type': 'multiple_choice',
            'opties': ['In beperkte mate', 'Net voldoende', 'Er was teveel nood aan persoonlijke ondersteuning'],
            'volgorde': 10,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Zijn er bepaalde onderwerpen waarover we in de toekomst zeker nog een Digicafé moeten organiseren?',
            'type': 'open_tekst',
            'opties': [],
            'volgorde': 11,
            'verplicht': True
        },
        {
            'vraag_tekst': 'Geef je eindscore: van 1 tot 10',
            'type': 'multiple_choice',
            'opties': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
            'volgorde': 12,
            'verplicht': True
        }
    ]

    act_types_table = sa.table(
        'activity_types',
        sa.column('id', sa.Integer),
        sa.column('organisatie_id', sa.Integer),
        sa.column('naam', sa.String),
        sa.column('heeft_evaluatie', sa.Boolean)
    )

    eval_forms_table = sa.table(
        'evaluatie_formulieren',
        sa.column('id', sa.Integer),
        sa.column('organisatie_id', sa.Integer),
        sa.column('activity_type_id', sa.Integer),
        sa.column('titel', sa.String),
        sa.column('toelichting', sa.Text),
        sa.column('actief', sa.Boolean),
        sa.column('aangemaakt_op', sa.DateTime),
        sa.column('gewijzigd_op', sa.DateTime)
    )

    eval_vragen_table = sa.table(
        'evaluatie_vragen',
        sa.column('id', sa.Integer),
        sa.column('form_id', sa.Integer),
        sa.column('vraag_tekst', sa.Text),
        sa.column('type', sa.String),
        sa.column('opties', sa.JSON),
        sa.column('volgorde', sa.Integer),
        sa.column('verplicht', sa.Boolean)
    )

    # Zet heeft_evaluatie = True voor Digicafé types
    connection.execute(
        act_types_table.update()
        .where(sa.func.lower(act_types_table.c.naam).like('%digicaf%'))
        .values(heeft_evaluatie=True)
    )
    
    # Haal alle Digicafé types op
    digicafe_types = connection.execute(
        sa.select(act_types_table.c.id, act_types_table.c.organisatie_id, act_types_table.c.naam)
        .where(sa.func.lower(act_types_table.c.naam).like('%digicaf%'))
    ).fetchall()

    for at_row in digicafe_types:
        at_id = at_row[0]
        org_id = at_row[1]
        at_naam = at_row[2]

        existing_form = connection.execute(
            sa.select(eval_forms_table.c.id)
            .where(
                eval_forms_table.c.activity_type_id == at_id,
                eval_forms_table.c.organisatie_id == org_id
            )
        ).fetchone()

        if not existing_form:
            connection.execute(
                eval_forms_table.insert().values(
                    organisatie_id=org_id,
                    activity_type_id=at_id,
                    titel=f"Evaluatie {at_naam}",
                    toelichting=f"Vul na afloop van het {at_naam} deze korte evaluatie in.",
                    actief=True,
                    aangemaakt_op=now_dt,
                    gewijzigd_op=now_dt
                )
            )
            form_row = connection.execute(
                sa.select(eval_forms_table.c.id)
                .where(
                    eval_forms_table.c.activity_type_id == at_id,
                    eval_forms_table.c.organisatie_id == org_id
                )
            ).fetchone()
            form_id = form_row[0]

            for v in digicafe_vragen:
                connection.execute(
                    eval_vragen_table.insert().values(
                        form_id=form_id,
                        vraag_tekst=v['vraag_tekst'],
                        type=v['type'],
                        opties=v['opties'],
                        volgorde=v['volgorde'],
                        verplicht=v['verplicht']
                    )
                )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.drop_column('heeft_evaluatie')

    with op.batch_alter_table('evaluatie_vragen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluatie_vragen_form_id'))

    op.drop_table('evaluatie_vragen')
    with op.batch_alter_table('evaluatie_uitnodigingen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluatie_uitnodigingen_token'))
        batch_op.drop_index(batch_op.f('ix_evaluatie_uitnodigingen_digidokter_id'))
        batch_op.drop_index(batch_op.f('ix_evaluatie_uitnodigingen_agenda_item_id'))

    op.drop_table('evaluatie_uitnodigingen')
    with op.batch_alter_table('evaluatie_reacties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluatie_reacties_user_id'))
        batch_op.drop_index(batch_op.f('ix_evaluatie_reacties_organisatie_id'))
        batch_op.drop_index(batch_op.f('ix_evaluatie_reacties_form_id'))
        batch_op.drop_index(batch_op.f('ix_evaluatie_reacties_digidokter_id'))
        batch_op.drop_index(batch_op.f('ix_evaluatie_reacties_agenda_item_id'))

    op.drop_table('evaluatie_reacties')
    with op.batch_alter_table('evaluatie_formulieren', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluatie_formulieren_organisatie_id'))
        batch_op.drop_index(batch_op.f('ix_evaluatie_formulieren_activity_type_id'))

    op.drop_table('evaluatie_formulieren')
    # ### end Alembic commands ###
