"""initial migration

Revision ID: 850e8dfeb533
Revises: 
Create Date: 2026-07-14 09:55:02.016012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850e8dfeb533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digidokters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('wachtwoord_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('moet_wachtwoord_wijzigen', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('laatste_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registratienummer', sa.String(length=20), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('client', sa.String(length=150), nullable=False),
    sa.Column('digidokter_id', sa.Integer(), nullable=False),
    sa.Column('nieuwe_klant', sa.Boolean(), nullable=False),
    sa.Column('herkomst', sa.String(length=200), nullable=True),
    sa.Column('onderwerp', sa.String(length=500), nullable=False),
    sa.Column('leeftijdscategorie_id', sa.Integer(), nullable=False),
    sa.Column('toestel_id', sa.Integer(), nullable=False),
    sa.Column('aangemaakt_door_id', sa.Integer(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aangemaakt_door_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['digidokter_id'], ['digidokters.id'], ),
    sa.ForeignKeyConstraint(['leeftijdscategorie_id'], ['age_categories.id'], ),
    sa.ForeignKeyConstraint(['toestel_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_registratienummer'), ['registratienummer'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_registratienummer'))

    op.drop_table('registrations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('digidokters')
    op.drop_table('devices')
    op.drop_table('age_categories')
    # ### end Alembic commands ###
