"""Voeg audit logs tabel toe

Revision ID: 8b27e2ddebf7
Revises: 71543a345569
Create Date: 2026-07-22 06:51:15.183476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b27e2ddebf7'
down_revision = '71543a345569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabel', sa.String(length=100), nullable=False),
    sa.Column('operatie', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('gebruiker', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('organisatie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
