"""Add recurring fields to agenda item

Revision ID: ad8c2bb96f21
Revises: dc82f1c4f734
Create Date: 2026-07-18 08:16:15.363993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8c2bb96f21'
down_revision = 'dc82f1c4f734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reeks_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_terugkerend', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('interval', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('einddatum', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda_items', schema=None) as batch_op:
        batch_op.drop_column('einddatum')
        batch_op.drop_column('interval')
        batch_op.drop_column('is_terugkerend')
        batch_op.drop_column('reeks_id')

    # ### end Alembic commands ###
