"""add_indexes_to_registrations

Revision ID: af67403ee61e
Revises: 7df2582f50b8
Create Date: 2026-07-26 20:46:13.138127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af67403ee61e'
down_revision = '7df2582f50b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_digidokter_id'), ['digidokter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_herkomst_id'), ['herkomst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_leeftijdscategorie_id'), ['leeftijdscategorie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_organisatie_id'), ['organisatie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_toestel_id'), ['toestel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_toestel_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_organisatie_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_leeftijdscategorie_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_herkomst_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_digidokter_id'))

    # ### end Alembic commands ###
