"""Add gender field to registrations

Revision ID: b837a9b70bbd
Revises: 3fc6cbbf9830
Create Date: 2026-07-15 22:23:31.280362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b837a9b70bbd'
down_revision = '3fc6cbbf9830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geslacht', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('geslacht')

    # ### end Alembic commands ###
