"""add app_mappen and app_documenten

Revision ID: bb850f7f1354
Revises: 5cb3b9c18368
Create Date: 2026-09-11 21:34:19.805468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb850f7f1354'
down_revision = '5cb3b9c18368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_mappen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('aangemaakt_door_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aangemaakt_door_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['app_mappen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_mappen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_mappen_parent_id'), ['parent_id'], unique=False)

    op.create_table('app_documenten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('bestandsnaam', sa.String(length=255), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('bestandsgrootte', sa.Integer(), nullable=False),
    sa.Column('inhoud', sa.LargeBinary(), nullable=False),
    sa.Column('tekst_inhoud', sa.Text(), nullable=True),
    sa.Column('versie', sa.Integer(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), nullable=False),
    sa.Column('aangemaakt_door_id', sa.Integer(), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(), nullable=False),
    sa.Column('gewijzigd_door_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aangemaakt_door_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gewijzigd_door_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['app_mappen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_documenten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_documenten_map_id'), ['map_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_documenten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_documenten_map_id'))

    op.drop_table('app_documenten')
    with op.batch_alter_table('app_mappen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_mappen_parent_id'))

    op.drop_table('app_mappen')
    # ### end Alembic commands ###
