"""Add agenda, activity types, locations

Revision ID: dc82f1c4f734
Revises: b837a9b70bbd
Create Date: 2026-07-18 07:51:23.939136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc82f1c4f734'
down_revision = 'b837a9b70bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisatie_id', 'naam', name='uq_activity_type_org_naam')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=150), nullable=False),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('volgorde', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisatie_id', 'naam', name='uq_location_org_naam')
    )
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('uur_van', sa.String(length=5), nullable=False),
    sa.Column('uur_tot', sa.String(length=5), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('locatie_id', sa.Integer(), nullable=False),
    sa.Column('omschrijving', sa.Text(), nullable=True),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locatie_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['activity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agenda_digidokters',
    sa.Column('agenda_item_id', sa.Integer(), nullable=False),
    sa.Column('digidokter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['digidokter_id'], ['digidokters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agenda_item_id', 'digidokter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda_digidokters')
    op.drop_table('agenda_items')
    op.drop_table('locations')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
